version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: keycloak
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    restart: always
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      KEYCLOAK_HTTP_ENABLED: true
      PROXY_ADDRESS_FORWARDING: true
      KC_PROXY: edge
      KC_HOSTNAME: 13.92.142.103
      KC_HOSTNAME_STRICT: false
    depends_on:
      - postgres

volumes:
  pgdata:
