---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create SSL dir
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'

- name: Generate self-signed cert
  command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout /etc/nginx/ssl/selfsigned.key
    -out /etc/nginx/ssl/selfsigned.crt
    -subj "/CN={{ ip_address }}"
  args:
    creates: /etc/nginx/ssl/selfsigned.crt

- name: Set nginx config for Keycloak
  copy:
    dest: /etc/nginx/sites-available/keycloak.conf
    content: |
      server {
          listen 443 ssl;
          server_name {{ ip_address }};

          ssl_certificate /etc/nginx/ssl/selfsigned.crt;
          ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

          ssl_protocols TLSv1.2 TLSv1.3;
          ssl_prefer_server_ciphers on;

          location / {
              proxy_pass http://localhost:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto https;
          }
      }

      server {
          listen 80;
          server_name {{ ip_address }};
          return 301 https://$host$request_uri;
      }
  notify: Restart nginx

- name: Enable nginx config
  file:
    src: /etc/nginx/sites-available/keycloak.conf
    dest: /etc/nginx/sites-enabled/keycloak.conf
    state: link
    force: yes

- name: Remove default nginx site if exists
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

