- name: Deploy Keycloak + Postgres + Nginx Proxy
  hosts: all
  become: true
  vars:
    docker_compose_dir: /opt/keycloak_compose
    ip_address: "{{ lookup('env','VM_IP') }}" 
  roles:
    - deploy_keycloak
    - nginx_keycloak_proxy  

  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      ignore_errors: true

    - name: Debug Docker version
      debug:
        msg: "{{ docker_check.stdout }}"

    - name: Check running Docker containers
      command: docker ps
      register: running_containers

    - name: Print running containers
      debug:
        msg: "{{ running_containers.stdout_lines }}"

    - name: Check docker-compose status
      command: docker compose ps
      args:
        chdir: "{{ docker_compose_dir }}"
      register: compose_status
      ignore_errors: true

    - name: Debug docker-compose ps output
      debug:
        var: compose_status.stdout_lines
