name: Run Ansible

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    env:
      VM_IP: ${{ secrets.VM_IP }}
      VM_USER: azureuser

    steps:
      - uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub

          ssh-keyscan -H "$VM_IP" >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: |
          ansible-playbook ansible/playbook.yml \
            -i "$VM_IP," \
            --private-key ~/.ssh/id_rsa \
            -u $VM_USER
